version: '2.2'
services:
  celery:
    build:
      context: .
      network: host
    # command: celery -A tasks worker --loglevel=info --logfile=tasks.log
    command: celery -A proj worker -l info --logfile=celeryapp.log
    volumes: 
      - .:/app
    environment:
      CELERY_CONN_STR: "${CELERY_CONN_STR}"
      PG_CONN_STR: "${PG_CONN_STR}"